/*Given an array of integers, find the pair of adjacent elements that has the largest product and return that product.ExampleFor inputArray = [3, 6, -2, -5, 7, 3], the output should be adjacentElementsProduct(inputArray) = 21.7 and 3 produce the largest product. */

function adjacentElementsProduct(inputArray) {
    var c =inputArray[0]*inputArray[1];
    var p = c;
    for(var i=1;i<inputArray.length;i++){
        console.log(c);
        var c=inputArray[i]*inputArray[i+1];
        if(c > p){
            p=c;
        };
    };
    return p;
};
console.log(adjacentElementsProduct([3,6,-2,-5,7,3]));

/*Transform hour to military formatGiven a time in -hour AM/PM format, convert it to military (-hour) time.

Note: Midnight is on a -hour clock, and on a -hour clock. Noon is on a -hour clock, and on a -hour clock.Input FormatA single string containing a time in -hour clock format (i.e.: or ), where 00 <= h <= 23 and 00 <= m <= 59.

Output FormatConvert and print the given time in -hour format, where .Sample Input = Sample Output07:05:45PM = 19:05:45 12:05:45AM = 00:05:45 12:05:45PM = 12:05:45 */

function timeConverter(time) {
 if(time.charAt(8)=="A"){
  if(time.substring(0,2)=="12") {
   return "00"+time.substring(2,8);
  }
   else{
     return time.substring(0,8);
   }
 }
  else{
    
    if(time.substring(0,2)=="12"){
      return time.substring(0,8);
    }
     else {
       return parseInt(time.substring(0,2))+12+        time.substring(2,8)
     }
  }
}
console.log(timeConverter("07:45:15AM"))
console.log(timeConverter("07:45:15PM"))
console.log(timeConverter("12:45:15AM"))
console.log(timeConverter("11:45:15PM"))

/*Sum of even fibonacci
Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be:1,1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 

...find the sum of the even-valued terms for all Fibonacci number less than 1000*/

var a = 1;
var b = 1 ;
var answer = 0;
//repitition control flow..it will repeat based on the number of time that specified
/*for (var i=0;i<10;i++){
  console.log(a)
  console.log(b)
  a = a+b
  b = b+a
}*/
//repetition control flow.. it will stop when you reach the goal which a & b <1000
while(a<1000 && b < 1000){
  if(a%2==0){
    
    answer += a
   }
  if(b%2==0){
   
    answer += b
  }
  a = a + b
  b = a + b
}
console.log(answer)
